"""
=============================================================================
File        : pe_plot.py
Project     : Processing Element (PE) – Benchmark Visualization
Platform    : Terasic DE10-Nano  (Intel Cyclone V SoC  5CSEBA6U23I7)

Description :
    Reads the CSV files generated by pe_benchmark.c and produces
    publication-quality figures suitable for IEEE/ACM papers.

    Figures generated:
      Fig 1 – Latency histogram with normal-fit overlay
      Fig 2 – CDF of latency (percentile curve)
      Fig 3 – Box plot: latency breakdown (total / comms / net compute)
      Fig 4 – Stacked bar: time breakdown per operation
      Fig 5 – Polling iteration histogram (pipeline determinism)
      Fig 6 – Throughput scaling projection (1x1 → NxN)
      Fig 7 – Combined summary dashboard (all metrics, one page)

    All figures saved as PDF (vector) + PNG 300 DPI.

Usage:
    pip install matplotlib numpy pandas scipy seaborn
    python3 pe_plot.py

    By default reads CSV files from the current directory.
    Edit INPUT_DIR and OUTPUT_DIR below if needed.

Author  : Daniel Fajardo
Date    : 2026-05-07
Version : 1.0
=============================================================================
"""

import os
import sys
import numpy  as np
import pandas as pd
import matplotlib
import matplotlib.pyplot   as plt
import matplotlib.patches  as mpatches
import matplotlib.ticker   as ticker
from   matplotlib.gridspec import GridSpec
from   scipy               import stats
import seaborn             as sns
import warnings
warnings.filterwarnings("ignore")

# =============================================================================
# Configuration
# =============================================================================

INPUT_DIR  = "."          # directory containing the CSV files
OUTPUT_DIR = "figures"    # output directory for PDFs and PNGs

FPGA_CLOCK_MHZ    = 50.0
FPGA_PERIOD_NS    = 1000.0 / FPGA_CLOCK_MHZ   # 20 ns

# Colors: IEEE-friendly palette (works in B&W print too)
C_TOTAL    = "#2C3E50"   # dark blue-grey  – total latency
C_COMMS    = "#E74C3C"   # red             – communication overhead
C_COMPUTE  = "#27AE60"   # green           – net compute
C_SW       = "#F39C12"   # orange          – software baseline
C_POLL     = "#8E44AD"   # purple          – polling
C_PROJ     = "#2980B9"   # blue            – projection

# Hatches for B&W printing
H_TOTAL   = ""
H_COMMS   = "////"
H_COMPUTE = "xxxx"
H_SW      = "++++"

# matplotlib style: clean IEEE look
matplotlib.rcParams.update({
    "font.family"       : "serif",
    "font.serif"        : ["Times New Roman", "DejaVu Serif"],
    "font.size"         : 10,
    "axes.titlesize"    : 11,
    "axes.labelsize"    : 10,
    "xtick.labelsize"   : 9,
    "ytick.labelsize"   : 9,
    "legend.fontsize"   : 9,
    "figure.dpi"        : 150,
    "savefig.dpi"       : 300,
    "savefig.bbox"      : "tight",
    "axes.grid"         : True,
    "grid.alpha"        : 0.3,
    "grid.linestyle"    : "--",
    "axes.spines.top"   : False,
    "axes.spines.right" : False,
})

# =============================================================================
# Helpers
# =============================================================================

def load_data():
    """Load all CSV files and return as a dict of DataFrames."""
    files = {
        "latency" : "pe_latency_samples.csv",
        "comms"   : "pe_comms_overhead.csv",
        "poll"    : "pe_poll_distribution.csv",
        "summary" : "pe_summary.txt",
    }
    data = {}
    for key, fname in files.items():
        path = os.path.join(INPUT_DIR, fname)
        if not os.path.exists(path):
            print(f"[WARN] Missing file: {path}")
            continue
        if fname.endswith(".csv"):
            data[key] = pd.read_csv(path)
            print(f"  Loaded {fname}  ({len(data[key])} rows)")
        else:
            with open(path) as f:
                data[key] = f.read()
            print(f"  Loaded {fname}")
    return data


def save_fig(fig, name):
    """Save figure as both PDF (vector) and PNG (300 Dpi)."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    pdf_path = os.path.join(OUTPUT_DIR, f"{name}.pdf")
    png_path = os.path.join(OUTPUT_DIR, f"{name}.png")
    fig.savefig(pdf_path, format="pdf")
    fig.savefig(png_path, format="png", dpi=300)
    print(f"  -> {pdf_path}  |  {png_path}")


def ns_to_cycles(ns):
    return ns / FPGA_PERIOD_NS


# =============================================================================
# Figure 1 – Latency histogram with normal-fit overlay
# =============================================================================

def plot_latency_histogram(data):
    lat = data["latency"]["latency_ns"].values

    fig, ax = plt.subplots(figsize=(5.5, 3.5))

    # Histogram (normalized to density)
    n_bins = min(50, int(np.sqrt(len(lat))))
    ax.hist(lat, bins=n_bins, density=True,
            color=C_TOTAL, alpha=0.7, edgecolor="white", linewidth=0.4,
            label="Measured samples")

    # Normal distribution fit
    mu, sigma = stats.norm.fit(lat)
    x = np.linspace(lat.min(), lat.max(), 400)
    ax.plot(x, stats.norm.pdf(x, mu, sigma),
            color="black", linewidth=1.5, linestyle="--",
            label=f"Normal fit  μ={mu:.0f} ns,  σ={sigma:.0f} ns")

    # Percentile markers
    p50 = np.percentile(lat, 50)
    p95 = np.percentile(lat, 95)
    ax.axvline(p50, color=C_COMPUTE, linewidth=1.2, linestyle="-.",
               label=f"P50 = {p50:.0f} ns")
    ax.axvline(p95, color=C_COMMS,   linewidth=1.2, linestyle="-.",
               label=f"P95 = {p95:.0f} ns")

    ax.set_xlabel("Latency (ns)")
    ax.set_ylabel("Probability Density")
    ax.set_title("Fig. 1 – IP_PE Operation Latency Distribution\n"
                 "(1×1 PE, LW-HPS2FPGA bridge, Linux userspace)")
    ax.legend(loc="upper right", framealpha=0.9)

    # Secondary x-axis in clock cycles
    ax2 = ax.twiny()
    ax2.set_xlim(np.array(ax.get_xlim()) / FPGA_PERIOD_NS)
    ax2.set_xlabel("Clock Cycles (@50 MHz)")
    ax2.tick_params(labelsize=8)

    fig.tight_layout()
    save_fig(fig, "fig1_latency_histogram")
    plt.close(fig)


# =============================================================================
# Figure 2 – CDF of latency
# =============================================================================

def plot_latency_cdf(data):
    lat = np.sort(data["latency"]["latency_ns"].values)
    cdf = np.arange(1, len(lat) + 1) / len(lat) * 100.0

    fig, ax = plt.subplots(figsize=(5.5, 3.5))

    ax.plot(lat, cdf, color=C_TOTAL, linewidth=1.8, label="Latency CDF")

    # Key percentile annotations
    for pct, color in [(50, C_COMPUTE), (90, C_SW), (95, C_COMMS), (99, "black")]:
        val = np.percentile(lat, pct)
        ax.axhline(pct, color=color, linewidth=0.8, linestyle="--", alpha=0.7)
        ax.axvline(val, color=color, linewidth=0.8, linestyle="--", alpha=0.7)
        ax.annotate(f"P{pct}\n{val:.0f} ns",
                    xy=(val, pct), xytext=(val + 200, pct - 8),
                    fontsize=7.5, color=color,
                    arrowprops=dict(arrowstyle="-", color=color, lw=0.6))

    ax.set_xlabel("Latency (ns)")
    ax.set_ylabel("Cumulative Probability (%)")
    ax.set_title("Fig. 2 – Latency CDF\n"
                 "(1×1 PE, 1 000 samples)")
    ax.set_ylim(0, 102)
    ax.yaxis.set_major_formatter(ticker.PercentFormatter())

    # Secondary x-axis in cycles
    ax2 = ax.twiny()
    ax2.set_xlim(np.array(ax.get_xlim()) / FPGA_PERIOD_NS)
    ax2.set_xlabel("Clock Cycles (@50 MHz)")
    ax2.tick_params(labelsize=8)

    ax.legend(loc="lower right")
    fig.tight_layout()
    save_fig(fig, "fig2_latency_cdf")
    plt.close(fig)


# =============================================================================
# Figure 3 – Box plot: latency breakdown
# =============================================================================

def plot_boxplot_breakdown(data):
    lat   = data["latency"]["latency_ns"].values
    comms = data["comms"]["comms_overhead_ns"].values
    net   = lat - comms.mean()        # net compute = total - mean comms

    # Build a tidy DataFrame for seaborn
    df = pd.DataFrame({
        "Latency (ns)" : np.concatenate([lat, comms, net]),
        "Component"    : (["Total Round-Trip"] * len(lat) +
                          ["Comms Overhead"]   * len(comms) +
                          ["Net Compute"]      * len(net)),
    })

    fig, ax = plt.subplots(figsize=(6, 4))

    palette = {"Total Round-Trip": C_TOTAL,
               "Comms Overhead"  : C_COMMS,
               "Net Compute"     : C_COMPUTE}

    sns.boxplot(data=df, x="Component", y="Latency (ns)",
                palette=palette, width=0.5, linewidth=1.2,
                flierprops=dict(marker=".", markersize=2, alpha=0.4),
                ax=ax)

    # Annotate medians
    for i, comp in enumerate(["Total Round-Trip", "Comms Overhead", "Net Compute"]):
        med = df[df["Component"] == comp]["Latency (ns)"].median()
        ax.text(i, med + 100, f"{med:.0f} ns\n({ns_to_cycles(med):.0f} cyc)",
                ha="center", va="bottom", fontsize=8, fontweight="bold")

    ax.set_title("Fig. 3 – Latency Breakdown: Total vs. Communication vs. Compute\n"
                 "(1×1 PE, 1 000 samples each)")
    ax.set_ylabel("Latency (ns)")
    ax.set_xlabel("")

    # B&W hatch overlay (for print)
    for patch, hatch in zip(ax.patches, [H_TOTAL, H_COMMS, H_COMPUTE]):
        patch.set_hatch(hatch)

    fig.tight_layout()
    save_fig(fig, "fig3_boxplot_breakdown")
    plt.close(fig)


# =============================================================================
# Figure 4 – Stacked bar: time breakdown per operation
# =============================================================================

def plot_stacked_bar(data):
    lat   = data["latency"]["latency_ns"].values
    comms = data["comms"]["comms_overhead_ns"].values

    mean_total  = lat.mean()
    mean_comms  = comms.mean()
    mean_net    = mean_total - mean_comms

    pct_comms   = 100.0 * mean_comms / mean_total
    pct_compute = 100.0 * mean_net   / mean_total

    fig, axes = plt.subplots(1, 2, figsize=(7, 3.5))

    # --- Left: absolute ns ---
    ax = axes[0]
    bars_ns = [mean_comms, mean_net]
    labels  = ["Comms Overhead", "Net Compute"]
    colors  = [C_COMMS, C_COMPUTE]
    hatches = [H_COMMS, H_COMPUTE]

    bottom = 0
    for val, lbl, col, hat in zip(bars_ns, labels, colors, hatches):
        b = ax.bar("1×1 PE", val, bottom=bottom,
                   color=col, edgecolor="black", linewidth=0.6,
                   hatch=hat, label=lbl, width=0.4)
        ax.text(0, bottom + val / 2,
                f"{val:.0f} ns\n({ns_to_cycles(val):.0f} cyc)",
                ha="center", va="center", fontsize=8.5,
                color="white", fontweight="bold")
        bottom += val

    ax.set_ylabel("Time per Operation (ns)")
    ax.set_title("Absolute Time Breakdown")
    ax.set_ylim(0, mean_total * 1.15)
    ax.legend(loc="upper right", framealpha=0.9)
    ax.set_xticks([])

    # --- Right: percentage ---
    ax2 = axes[1]
    wedges, texts, autotexts = ax2.pie(
        [pct_comms, pct_compute],
        labels=["Comms\nOverhead", "Net\nCompute"],
        colors=[C_COMMS, C_COMPUTE],
        autopct="%1.1f%%",
        startangle=90,
        wedgeprops=dict(edgecolor="black", linewidth=0.8),
        textprops=dict(fontsize=9),
    )
    for at in autotexts:
        at.set_fontsize(9)
        at.set_fontweight("bold")
    ax2.set_title("Percentage Breakdown")

    fig.suptitle("Fig. 4 – Time Breakdown per MAC Operation  (1×1 PE)",
                 fontsize=11, fontweight="bold", y=1.02)
    fig.tight_layout()
    save_fig(fig, "fig4_time_breakdown")
    plt.close(fig)


# =============================================================================
# Figure 5 – Polling iteration histogram (pipeline determinism)
# =============================================================================

def plot_poll_histogram(data):
    poll_df = data["poll"]
    polls   = np.repeat(poll_df["poll_count"].values,
                        poll_df["frequency"].values)

    fig, ax = plt.subplots(figsize=(5.5, 3.5))

    bins = np.arange(polls.min() - 0.5, polls.max() + 1.5, 1)
    ax.hist(polls, bins=bins, color=C_POLL, edgecolor="white",
            linewidth=0.5, density=False, label="Poll count frequency")

    mode_val = poll_df.loc[poll_df["frequency"].idxmax(), "poll_count"]
    ax.axvline(mode_val, color="black", linewidth=1.5, linestyle="--",
               label=f"Mode = {mode_val} iterations")

    ax.set_xlabel("ip_ready Polling Iterations per Operation")
    ax.set_ylabel("Frequency (out of 1 000 samples)")
    ax.set_title("Fig. 5 – ip_ready Polling Distribution\n"
                 "(validates FSM pipeline determinism)")
    ax.legend()

    # Annotate expected pipeline depth
    expected = int((5 + 2 + 3))  # MULT + SIGN + ADD cycles
    ax.axvline(expected, color=C_COMPUTE, linewidth=1.2, linestyle="-.",
               label=f"Expected pipeline depth ≈ {expected} cyc")
    ax.legend()

    fig.tight_layout()
    save_fig(fig, "fig5_poll_histogram")
    plt.close(fig)


# =============================================================================
# Figure 6 – Throughput scaling projection (1×1 → N×N)
# =============================================================================

def plot_throughput_scaling(data):
    lat   = data["latency"]["latency_ns"].values
    comms = data["comms"]["comms_overhead_ns"].values

    measured_mops_1x1 = 0.1598   # from benchmark output

    # Theoretical model:
    # For an N×N array: N² MACs share ONE bridge transaction overhead.
    # Projected throughput = N² / (comms_mean + N² * compute_per_mac_ns) * 1e3
    mean_comms   = comms.mean()
    mean_compute = lat.mean() - mean_comms    # net compute for 1 MAC

    N_values = np.array([1, 2, 3, 4, 5, 6, 7, 8])
    macs     = N_values ** 2

    # Model: same comms overhead, compute scales with N²
    throughput_projected = macs / (mean_comms + macs * mean_compute) * 1e6  # MOPS

    # Ideal (no comms overhead)
    throughput_ideal = macs / (macs * mean_compute) * 1e6

    fig, ax = plt.subplots(figsize=(6, 4))

    ax.plot(macs, throughput_projected, "o-",
            color=C_PROJ, linewidth=2, markersize=6,
            label="Projected (with bridge overhead)")
    ax.plot(macs, throughput_ideal, "s--",
            color=C_COMPUTE, linewidth=1.5, markersize=5,
            label="Ideal (compute only, no comms)")
    ax.axhline(measured_mops_1x1, color=C_COMMS, linewidth=1.2,
               linestyle="-.", label=f"Measured 1×1 = {measured_mops_1x1:.3f} MOPS")

    # Annotate array sizes
    for n, mac, thr in zip(N_values, macs, throughput_projected):
        ax.annotate(f"{n}×{n}",
                    xy=(mac, thr), xytext=(mac + 0.3, thr * 1.06),
                    fontsize=8, color=C_PROJ)

    ax.set_xlabel("Number of MACs (N²  for N×N array)")
    ax.set_ylabel("Throughput (MOPS)")
    ax.set_title("Fig. 6 – Throughput Scaling Projection\n"
                 "(fixed bridge overhead amortised over N² MACs)")
    ax.legend(loc="upper left")
    ax.set_xlim(0, macs[-1] + 2)
    ax.set_ylim(0, throughput_ideal[-1] * 1.15)

    # Mark crossover with SW (1052 ns per op software)
    sw_mops = 1.0 / (1052.8e-9) / 1e6
    ax.axhline(sw_mops, color=C_SW, linewidth=1.2, linestyle=":",
               label=f"SW baseline = {sw_mops:.3f} MOPS")
    ax.legend(loc="upper left")

    fig.tight_layout()
    save_fig(fig, "fig6_throughput_scaling")
    plt.close(fig)


# =============================================================================
# Figure 7 – Combined summary dashboard
# =============================================================================

def plot_dashboard(data):
    lat   = data["latency"]["latency_ns"].values
    comms = data["comms"]["comms_overhead_ns"].values

    fig = plt.figure(figsize=(12, 8))
    gs  = GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.38)

    # ── Top-left: histogram ──────────────────────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    n_bins = min(40, int(np.sqrt(len(lat))))
    ax1.hist(lat, bins=n_bins, density=True,
             color=C_TOTAL, alpha=0.75, edgecolor="white", linewidth=0.3)
    mu, sigma = stats.norm.fit(lat)
    x = np.linspace(lat.min(), lat.max(), 300)
    ax1.plot(x, stats.norm.pdf(x, mu, sigma), "k--", linewidth=1.2)
    ax1.set_title("Latency Distribution")
    ax1.set_xlabel("ns");  ax1.set_ylabel("Density")

    # ── Top-center: CDF ──────────────────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    lat_s = np.sort(lat)
    cdf   = np.arange(1, len(lat_s) + 1) / len(lat_s) * 100
    ax2.plot(lat_s, cdf, color=C_TOTAL, linewidth=1.5)
    for pct, col in [(50, C_COMPUTE), (95, C_COMMS)]:
        val = np.percentile(lat, pct)
        ax2.axvline(val, color=col, linewidth=0.9, linestyle="--",
                    label=f"P{pct}={val:.0f}ns")
    ax2.set_title("Latency CDF")
    ax2.set_xlabel("ns");  ax2.set_ylabel("%")
    ax2.yaxis.set_major_formatter(ticker.PercentFormatter())
    ax2.legend(fontsize=8)

    # ── Top-right: stacked bar ───────────────────────────────────────────
    ax3 = fig.add_subplot(gs[0, 2])
    mean_comms = comms.mean()
    mean_net   = lat.mean() - mean_comms
    bottom = 0
    for val, lbl, col, hat in [(mean_comms, "Comms", C_COMMS,   H_COMMS),
                                (mean_net,   "Compute", C_COMPUTE, H_COMPUTE)]:
        ax3.bar("1×1", val, bottom=bottom, color=col, edgecolor="black",
                linewidth=0.5, hatch=hat, label=lbl, width=0.4)
        ax3.text(0, bottom + val / 2, f"{val:.0f}ns",
                 ha="center", va="center", fontsize=8,
                 color="white", fontweight="bold")
        bottom += val
    ax3.set_title("Time Breakdown")
    ax3.set_ylabel("ns");  ax3.set_xticks([])
    ax3.legend(fontsize=8)

    # ── Bottom-left: box plot ────────────────────────────────────────────
    ax4 = fig.add_subplot(gs[1, 0])
    net = lat - mean_comms
    ax4.boxplot([lat, comms, net],
                labels=["Total", "Comms", "Compute"],
                patch_artist=True,
                boxprops=dict(facecolor="lightgrey"),
                medianprops=dict(color="black", linewidth=1.5),
                flierprops=dict(marker=".", markersize=2, alpha=0.3))
    ax4.set_title("Latency Box Plot")
    ax4.set_ylabel("ns")

    # ── Bottom-center: poll histogram ────────────────────────────────────
    ax5 = fig.add_subplot(gs[1, 1])
    poll_df = data["poll"]
    polls   = np.repeat(poll_df["poll_count"].values,
                        poll_df["frequency"].values)
    bins = np.arange(polls.min() - 0.5, polls.max() + 1.5, 1)
    ax5.hist(polls, bins=bins, color=C_POLL, edgecolor="white", linewidth=0.4)
    ax5.set_title("Polling Distribution")
    ax5.set_xlabel("Iterations");  ax5.set_ylabel("Count")

    # ── Bottom-right: scaling projection ────────────────────────────────
    ax6 = fig.add_subplot(gs[1, 2])
    N_values = np.arange(1, 9)
    macs     = N_values ** 2
    thr_proj = macs / (mean_comms + macs * mean_net) * 1e6
    ax6.plot(macs, thr_proj, "o-", color=C_PROJ, linewidth=1.8, markersize=5)
    ax6.axhline(1.0 / (1052.8e-9) / 1e6, color=C_SW, linewidth=1,
                linestyle=":", label="SW baseline")
    ax6.set_title("Throughput Scaling")
    ax6.set_xlabel("MACs (N²)");  ax6.set_ylabel("MOPS")
    ax6.legend(fontsize=8)

    fig.suptitle(
        "IP_PE Benchmark Dashboard  –  DE10-Nano  Cyclone V 5CSEBA6U23I7\n"
        "Operands: A=15, B=−7  |  50 MHz  |  LW-HPS2FPGA bridge  |  1 000 samples",
        fontsize=11, fontweight="bold"
    )

    save_fig(fig, "fig7_dashboard")
    plt.close(fig)


# =============================================================================
# Entry point
# =============================================================================

def main():
    print("\n" + "=" * 60)
    print("  IP_PE Benchmark Plotter  v1.0")
    print("  Output format: PDF (vector) + PNG 300 DPI")
    print("=" * 60 + "\n")

    print("Loading data:")
    data = load_data()

    required = ["latency", "comms", "poll"]
    for key in required:
        if key not in data:
            print(f"\n[ERROR] Missing dataset '{key}'. "
                  f"Run pe_benchmark first.\n")
            sys.exit(1)

    print(f"\nGenerating figures → ./{OUTPUT_DIR}/\n")

    plot_latency_histogram (data)
    plot_latency_cdf       (data)
    plot_boxplot_breakdown (data)
    plot_stacked_bar       (data)
    plot_poll_histogram    (data)
    plot_throughput_scaling(data)
    plot_dashboard         (data)

    print(f"\n{'='*60}")
    print(f"  Done. 7 figures saved to ./{OUTPUT_DIR}/")
    print(f"  Files: PDF (vector, for paper) + PNG (300 DPI, for review)")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()