"""
=============================================================================
File        : sa3x3_plot.py
Project     : CSNE-SoC – 3×3 Systolic MAC Array Benchmark Visualization
Platform    : Terasic DE10-Nano  (Intel Cyclone V SoC  5CSEBA6U23I7)

Description :
    Reads the CSV files generated by sa3x3_benchmark.c and produces
    publication-quality figures suitable for IEEE/ACM papers.
    Mirrors pe_plot.py (1×1) in style for direct comparison.

    Figures generated:
      Fig 1 – Latency histogram with normal-fit overlay
      Fig 2 – CDF of latency (percentile curve)
      Fig 3 – Box plot: latency breakdown (total / comms / net compute)
      Fig 4 – Stacked bar + pie: time breakdown per matrix multiply
      Fig 5 – Poll distribution histogram (pipeline determinism)
      Fig 6 – 1×1 vs 3×3 comparison (latency per MAC + throughput)
      Fig 7 – Throughput scaling projection (1×1 → N×N)
      Fig 8 – Combined summary dashboard (all metrics, one page)

    All figures saved as PDF (vector) + PNG 300 DPI.

Usage:
    pip install matplotlib numpy pandas scipy seaborn
    python3 sa3x3_plot.py

    Place sa3x3_*.csv files in the same directory (or edit INPUT_DIR).

Author  : Daniel G. Fajardo Lopez
Date    : 2026-05-11
Version : 1.0
=============================================================================
"""

import os
import sys
import numpy  as np
import pandas as pd
import matplotlib
import matplotlib.pyplot  as plt
import matplotlib.ticker  as ticker
from   matplotlib.gridspec import GridSpec
from   scipy              import stats
import seaborn            as sns
import warnings
warnings.filterwarnings("ignore")

# =============================================================================
# Configuration
# =============================================================================

INPUT_DIR  = "."
OUTPUT_DIR = "figures_3x3"

FPGA_CLOCK_MHZ   = 50.0
FPGA_PERIOD_NS   = 1000.0 / FPGA_CLOCK_MHZ   # 20 ns

# Measured 1×1 reference values (from pe_benchmark results)
REF_1x1_LATENCY_NS   = 7390.7   # mean latency per operation (= 1 MAC)
REF_1x1_COMMS_NS     = 3036.4   # comms overhead
REF_1x1_THROUGHPUT   = 0.160    # MOPS
REF_1x1_SW_NS        = 1052.8   # SW baseline per MAC

# 3×3 constants
N_PES        = 9     # 3×3 = 9 processing elements
N_KSLICES    = 3     # k-slices per matrix multiply

# IEEE-friendly color palette (works in B&W print)
C_TOTAL   = "#2C3E50"   # dark blue-grey
C_COMMS   = "#E74C3C"   # red
C_COMPUTE = "#27AE60"   # green
C_SW      = "#F39C12"   # orange
C_POLL    = "#8E44AD"   # purple
C_PROJ    = "#2980B9"   # blue
C_1x1     = "#E74C3C"   # red   (1×1 reference)
C_3x3     = "#27AE60"   # green (3×3 result)

H_TOTAL   = ""
H_COMMS   = "////"
H_COMPUTE = "xxxx"

matplotlib.rcParams.update({
    "font.family"       : "serif",
    "font.serif"        : ["Times New Roman", "DejaVu Serif"],
    "font.size"         : 10,
    "axes.titlesize"    : 11,
    "axes.labelsize"    : 10,
    "xtick.labelsize"   : 9,
    "ytick.labelsize"   : 9,
    "legend.fontsize"   : 9,
    "figure.dpi"        : 150,
    "savefig.dpi"       : 300,
    "savefig.bbox"      : "tight",
    "axes.grid"         : True,
    "grid.alpha"        : 0.3,
    "grid.linestyle"    : "--",
    "axes.spines.top"   : False,
    "axes.spines.right" : False,
})

# =============================================================================
# Helpers
# =============================================================================

def load_data():
    files = {
        "latency" : "sa3x3_latency_samples.csv",
        "comms"   : "sa3x3_comms_overhead.csv",
        "poll"    : "sa3x3_poll_distribution.csv",
    }
    data = {}
    for key, fname in files.items():
        path = os.path.join(INPUT_DIR, fname)
        if not os.path.exists(path):
            print(f"[WARN] Missing: {path}")
            continue
        data[key] = pd.read_csv(path)
        print(f"  Loaded {fname}  ({len(data[key])} rows)")
    return data


def save_fig(fig, name):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    pdf = os.path.join(OUTPUT_DIR, f"{name}.pdf")
    png = os.path.join(OUTPUT_DIR, f"{name}.png")
    fig.savefig(pdf, format="pdf")
    fig.savefig(png, format="png", dpi=300)
    print(f"  -> {pdf}  |  {png}")


def ns_to_cycles(ns):
    return ns / FPGA_PERIOD_NS


def add_cycle_axis(ax):
    """Add secondary x-axis in clock cycles."""
    ax2 = ax.twiny()
    ax2.set_xlim(np.array(ax.get_xlim()) / FPGA_PERIOD_NS)
    ax2.set_xlabel("Clock Cycles (@50 MHz)")
    ax2.tick_params(labelsize=8)
    return ax2


# =============================================================================
# Fig 1 – Latency histogram with normal-fit
# =============================================================================
def plot_latency_histogram(data):
    lat = data["latency"]["latency_ns"].values

    fig, ax = plt.subplots(figsize=(5.5, 3.5))

    n_bins = min(50, int(np.sqrt(len(lat))))
    ax.hist(lat, bins=n_bins, density=True,
            color=C_TOTAL, alpha=0.7, edgecolor="white", linewidth=0.4,
            label="Measured samples")

    mu, sigma = stats.norm.fit(lat)
    x = np.linspace(lat.min(), lat.max(), 400)
    ax.plot(x, stats.norm.pdf(x, mu, sigma), "k--", linewidth=1.5,
            label=f"Normal fit  μ={mu:.0f} ns,  σ={sigma:.0f} ns")

    for pct, color, ls in [(50, C_COMPUTE, "-."), (95, C_COMMS, "-.")]:
        val = np.percentile(lat, pct)
        ax.axvline(val, color=color, linewidth=1.2, linestyle=ls,
                   label=f"P{pct} = {val:.0f} ns")

    ax.set_xlabel("Latency per 3×3 Matrix Multiply (ns)")
    ax.set_ylabel("Probability Density")
    ax.set_title("Fig. 1 – 3×3 Array Latency Distribution\n"
                 "(1 000 matrix multiplies, flush each, LW-HPS2FPGA bridge)")
    ax.legend(loc="upper right", framealpha=0.9)
    add_cycle_axis(ax)

    fig.tight_layout()
    save_fig(fig, "fig1_latency_histogram")
    plt.close(fig)


# =============================================================================
# Fig 2 – CDF of latency
# =============================================================================
def plot_latency_cdf(data):
    lat = np.sort(data["latency"]["latency_ns"].values)
    cdf = np.arange(1, len(lat) + 1) / len(lat) * 100.0

    fig, ax = plt.subplots(figsize=(5.5, 3.5))

    ax.plot(lat, cdf, color=C_TOTAL, linewidth=1.8, label="Latency CDF")

    for pct, color in [(50, C_COMPUTE), (90, C_SW), (95, C_COMMS), (99, "black")]:
        val = np.percentile(lat, pct)
        ax.axhline(pct, color=color, linewidth=0.8, linestyle="--", alpha=0.7)
        ax.axvline(val, color=color, linewidth=0.8, linestyle="--", alpha=0.7)
        ax.annotate(f"P{pct}\n{val:.0f} ns",
                    xy=(val, pct), xytext=(val + 300, pct - 8),
                    fontsize=7.5, color=color,
                    arrowprops=dict(arrowstyle="-", color=color, lw=0.6))

    ax.set_xlabel("Latency per 3×3 Matrix Multiply (ns)")
    ax.set_ylabel("Cumulative Probability (%)")
    ax.set_title("Fig. 2 – Latency CDF  (3×3 Array, 1 000 samples)")
    ax.set_ylim(0, 102)
    ax.yaxis.set_major_formatter(ticker.PercentFormatter())
    ax.legend(loc="lower right")
    add_cycle_axis(ax)

    fig.tight_layout()
    save_fig(fig, "fig2_latency_cdf")
    plt.close(fig)


# =============================================================================
# Fig 3 – Box plot: latency breakdown
# =============================================================================
def plot_boxplot_breakdown(data):
    lat   = data["latency"]["latency_ns"].values
    comms = data["comms"]["comms_overhead_ns"].values
    net   = lat - comms.mean()

    df = pd.DataFrame({
        "Latency (ns)" : np.concatenate([lat, comms, net]),
        "Component"    : (["Total Round-Trip"] * len(lat) +
                          ["Comms Overhead"]   * len(comms) +
                          ["Net Compute"]      * len(net)),
    })

    fig, ax = plt.subplots(figsize=(6, 4))

    palette = {"Total Round-Trip": C_TOTAL,
               "Comms Overhead"  : C_COMMS,
               "Net Compute"     : C_COMPUTE}

    sns.boxplot(data=df, x="Component", y="Latency (ns)",
                palette=palette, width=0.5, linewidth=1.2,
                flierprops=dict(marker=".", markersize=2, alpha=0.4),
                ax=ax)

    for i, comp in enumerate(["Total Round-Trip", "Comms Overhead", "Net Compute"]):
        med = df[df["Component"] == comp]["Latency (ns)"].median()
        ax.text(i, med + 200, f"{med:.0f} ns\n({ns_to_cycles(med):.0f} cyc)",
                ha="center", va="bottom", fontsize=8, fontweight="bold")

    ax.set_title("Fig. 3 – Latency Breakdown: Total vs. Comms vs. Net Compute\n"
                 "(3×3 Array, 1 000 samples each)")
    ax.set_ylabel("Latency (ns)")
    ax.set_xlabel("")

    for patch, hatch in zip(ax.patches, [H_TOTAL, H_COMMS, H_COMPUTE]):
        patch.set_hatch(hatch)

    fig.tight_layout()
    save_fig(fig, "fig3_boxplot_breakdown")
    plt.close(fig)


# =============================================================================
# Fig 4 – Stacked bar + pie: time breakdown
# =============================================================================
def plot_stacked_bar(data):
    lat   = data["latency"]["latency_ns"].values
    comms = data["comms"]["comms_overhead_ns"].values

    mean_total  = lat.mean()
    mean_comms  = comms.mean()
    mean_net    = mean_total - mean_comms

    pct_comms   = 100.0 * mean_comms / mean_total
    pct_compute = 100.0 * mean_net   / mean_total

    fig, axes = plt.subplots(1, 2, figsize=(7, 3.5))

    # Left: absolute ns
    ax = axes[0]
    bottom = 0
    for val, lbl, col, hat in [(mean_comms, "Comms Overhead", C_COMMS, H_COMMS),
                                (mean_net,   "Net Compute",   C_COMPUTE, H_COMPUTE)]:
        ax.bar("3×3 Array", val, bottom=bottom,
               color=col, edgecolor="black", linewidth=0.6,
               hatch=hat, label=lbl, width=0.4)
        ax.text(0, bottom + val / 2,
                f"{val:.0f} ns\n({ns_to_cycles(val):.0f} cyc)",
                ha="center", va="center", fontsize=8.5,
                color="white", fontweight="bold")
        bottom += val

    ax.set_ylabel("Time per Matrix Multiply (ns)")
    ax.set_title("Absolute Time Breakdown")
    ax.set_ylim(0, mean_total * 1.15)
    ax.legend(loc="upper right", framealpha=0.9)
    ax.set_xticks([])

    # Right: pie
    ax2 = axes[1]
    wedges, texts, autotexts = ax2.pie(
        [pct_comms, pct_compute],
        labels=["Comms\nOverhead", "Net\nCompute"],
        colors=[C_COMMS, C_COMPUTE],
        autopct="%1.1f%%", startangle=90,
        wedgeprops=dict(edgecolor="black", linewidth=0.8),
        textprops=dict(fontsize=9),
    )
    for at in autotexts:
        at.set_fontsize(9); at.set_fontweight("bold")
    ax2.set_title("Percentage Breakdown")

    fig.suptitle("Fig. 4 – Time Breakdown per Matrix Multiply  (3×3 Array)",
                 fontsize=11, fontweight="bold", y=1.02)
    fig.tight_layout()
    save_fig(fig, "fig4_time_breakdown")
    plt.close(fig)


# =============================================================================
# Fig 5 – Poll distribution
# =============================================================================
def plot_poll_histogram(data):
    poll_df = data["poll"]
    polls   = np.repeat(poll_df["total_poll_count"].values,
                        poll_df["frequency"].values)

    fig, ax = plt.subplots(figsize=(5.5, 3.5))

    bins = np.arange(polls.min() - 0.5, polls.max() + 1.5, 1)
    ax.hist(polls, bins=bins, color=C_POLL, edgecolor="white",
            linewidth=0.5, label="Poll count frequency")

    mode_val = poll_df.loc[poll_df["frequency"].idxmax(), "total_poll_count"]
    ax.axvline(mode_val, color="black", linewidth=1.5, linestyle="--",
               label=f"Mode = {mode_val} total iterations (3 k-slices)")

    ax.set_xlabel("Total ip_ready Poll Iterations per Matrix Multiply")
    ax.set_ylabel("Frequency (out of 1 000 samples)")
    ax.set_title("Fig. 5 – Poll Count Distribution\n"
                 "(sum of 3 k-slice polls per matrix multiply)")
    ax.legend()

    fig.tight_layout()
    save_fig(fig, "fig5_poll_histogram")
    plt.close(fig)


# =============================================================================
# Fig 6 – 1×1 vs 3×3 direct comparison
# =============================================================================
def plot_comparison_1x1_vs_3x3(data):
    lat   = data["latency"]["latency_ns"].values
    comms = data["comms"]["comms_overhead_ns"].values

    mean_lat_3x3    = lat.mean()
    mean_comms_3x3  = comms.mean()
    mean_net_3x3    = mean_lat_3x3 - mean_comms_3x3

    # Per-MAC values
    lat_per_mac_1x1   = REF_1x1_LATENCY_NS        # 1 MAC
    lat_per_mac_3x3   = mean_lat_3x3 / N_PES      # 9 MACs

    comms_per_mac_1x1 = REF_1x1_COMMS_NS
    comms_per_mac_3x3 = mean_comms_3x3 / N_PES

    net_per_mac_1x1   = REF_1x1_LATENCY_NS - REF_1x1_COMMS_NS
    net_per_mac_3x3   = mean_net_3x3 / N_PES

    fig, axes = plt.subplots(1, 2, figsize=(9, 4))

    # --- Left: latency per MAC comparison ---
    ax = axes[0]
    x     = np.array([0, 1])
    width = 0.25

    b1 = ax.bar(x - width, [lat_per_mac_1x1,   lat_per_mac_3x3],
                width, color=C_TOTAL,   edgecolor="black", linewidth=0.6,
                hatch=H_TOTAL,   label="Total latency/MAC")
    b2 = ax.bar(x,         [comms_per_mac_1x1, comms_per_mac_3x3],
                width, color=C_COMMS,   edgecolor="black", linewidth=0.6,
                hatch=H_COMMS,   label="Comms overhead/MAC")
    b3 = ax.bar(x + width, [net_per_mac_1x1,   net_per_mac_3x3],
                width, color=C_COMPUTE, edgecolor="black", linewidth=0.6,
                hatch=H_COMPUTE, label="Net compute/MAC")

    # Annotate bars
    for bar_group in [b1, b2, b3]:
        for bar in bar_group:
            h = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2, h + 50,
                    f"{h:.0f}",
                    ha="center", va="bottom", fontsize=7.5)

    ax.set_xticks(x)
    ax.set_xticklabels(["1×1 PE\n(1 MAC)", "3×3 Array\n(9 MACs)"])
    ax.set_ylabel("Time per MAC (ns)")
    ax.set_title("Latency per MAC: 1×1 vs 3×3")
    ax.legend(loc="upper right", fontsize=8)

    improvement = lat_per_mac_1x1 / lat_per_mac_3x3
    ax.text(0.5, 0.95,
            f"3×3 is {improvement:.1f}× more efficient\nper MAC than 1×1",
            transform=ax.transAxes, ha="center", va="top",
            fontsize=9, color=C_COMPUTE,
            bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                      edgecolor=C_COMPUTE, alpha=0.8))

    # --- Right: throughput comparison ---
    ax2 = axes[1]
    categories = ["1×1 PE", "3×3 Array"]
    throughputs = [REF_1x1_THROUGHPUT, 0.2585]  # MOPS from benchmark

    bars = ax2.bar(categories, throughputs,
                   color=[C_1x1, C_3x3], edgecolor="black", linewidth=0.6,
                   width=0.4)

    for bar, val in zip(bars, throughputs):
        ax2.text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 0.005,
                 f"{val:.3f} MOPS",
                 ha="center", va="bottom", fontsize=9, fontweight="bold")

    ax2.set_ylabel("Throughput (MOPS)")
    ax2.set_title("Throughput: 1×1 vs 3×3")

    speedup_thr = 0.2585 / REF_1x1_THROUGHPUT
    ax2.text(0.5, 0.85,
             f"{speedup_thr:.1f}× throughput\nimprovement",
             transform=ax2.transAxes, ha="center",
             fontsize=9, color=C_3x3,
             bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                       edgecolor=C_3x3, alpha=0.8))

    fig.suptitle("Fig. 6 – 1×1 PE vs 3×3 Array: Efficiency Comparison",
                 fontsize=11, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, "fig6_comparison_1x1_vs_3x3")
    plt.close(fig)


# =============================================================================
# Fig 7 – Throughput scaling projection (1×1 → N×N)
# =============================================================================
def plot_throughput_scaling(data):
    lat   = data["latency"]["latency_ns"].values
    comms = data["comms"]["comms_overhead_ns"].values

    mean_comms  = comms.mean()
    mean_net    = lat.mean() - mean_comms

    # Net compute per MAC (amortised)
    net_per_mac = mean_net / N_PES

    N_values = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
    macs     = N_values ** 2

    # Model: comms overhead fixed, compute scales with N²
    thr_projected = macs / (mean_comms + macs * net_per_mac) * 1e6  # MOPS
    thr_ideal     = macs / (macs * net_per_mac) * 1e6               # no comms

    sw_mops_per_mac = 1.0 / (REF_1x1_SW_NS * 1e-9) / 1e6

    fig, ax = plt.subplots(figsize=(6, 4))

    ax.plot(macs, thr_projected, "o-",
            color=C_PROJ, linewidth=2, markersize=6,
            label="Projected (with bridge overhead)")
    ax.plot(macs, thr_ideal, "s--",
            color=C_COMPUTE, linewidth=1.5, markersize=5,
            label="Ideal (no comms overhead)")

    # Measured points
    ax.scatter([1], [REF_1x1_THROUGHPUT], color=C_1x1, s=80, zorder=5,
               label=f"Measured 1×1 = {REF_1x1_THROUGHPUT:.3f} MOPS")
    ax.scatter([9], [0.2585], color=C_3x3, s=80, zorder=5,
               label=f"Measured 3×3 = 0.258 MOPS")

    ax.axhline(sw_mops_per_mac, color=C_SW, linewidth=1.2, linestyle=":",
               label=f"SW baseline ≈ {sw_mops_per_mac:.3f} MOPS/MAC")

    # Annotate array sizes
    for n, mac, thr in zip(N_values, macs, thr_projected):
        ax.annotate(f"{n}×{n}",
                    xy=(mac, thr), xytext=(mac + 0.3, thr * 1.05),
                    fontsize=8, color=C_PROJ)

    ax.set_xlabel("Number of MACs (N² for N×N array)")
    ax.set_ylabel("Throughput (MOPS)")
    ax.set_title("Fig. 7 – Throughput Scaling Projection\n"
                 "(fixed bridge overhead amortised over N² MACs)\n"
                 "● Measured points  — Projected  -- Ideal")
    ax.legend(loc="upper left", fontsize=8)
    ax.set_xlim(0, macs[-1] + 2)

    fig.tight_layout()
    save_fig(fig, "fig7_throughput_scaling")
    plt.close(fig)


# =============================================================================
# Fig 8 – Combined dashboard
# =============================================================================
def plot_dashboard(data):
    lat   = data["latency"]["latency_ns"].values
    comms = data["comms"]["comms_overhead_ns"].values

    mean_comms = comms.mean()
    mean_net   = lat.mean() - mean_comms
    net_per_mac = mean_net / N_PES

    fig = plt.figure(figsize=(14, 9))
    gs  = GridSpec(2, 4, figure=fig, hspace=0.45, wspace=0.38)

    # ── Histogram ────────────────────────────────────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    n_bins = min(40, int(np.sqrt(len(lat))))
    ax1.hist(lat, bins=n_bins, density=True,
             color=C_TOTAL, alpha=0.75, edgecolor="white", linewidth=0.3)
    mu, sigma = stats.norm.fit(lat)
    x = np.linspace(lat.min(), lat.max(), 300)
    ax1.plot(x, stats.norm.pdf(x, mu, sigma), "k--", linewidth=1.2)
    ax1.set_title("Latency Distribution"); ax1.set_xlabel("ns"); ax1.set_ylabel("Density")

    # ── CDF ──────────────────────────────────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    lat_s = np.sort(lat)
    cdf   = np.arange(1, len(lat_s) + 1) / len(lat_s) * 100
    ax2.plot(lat_s, cdf, color=C_TOTAL, linewidth=1.5)
    for pct, col in [(50, C_COMPUTE), (95, C_COMMS)]:
        val = np.percentile(lat, pct)
        ax2.axvline(val, color=col, linewidth=0.9, linestyle="--",
                    label=f"P{pct}={val:.0f}ns")
    ax2.set_title("Latency CDF"); ax2.set_xlabel("ns"); ax2.set_ylabel("%")
    ax2.yaxis.set_major_formatter(ticker.PercentFormatter())
    ax2.legend(fontsize=7)

    # ── Stacked bar ───────────────────────────────────────────────────────────
    ax3 = fig.add_subplot(gs[0, 2])
    bottom = 0
    for val, lbl, col, hat in [(mean_comms, "Comms", C_COMMS, H_COMMS),
                                (mean_net,   "Compute", C_COMPUTE, H_COMPUTE)]:
        ax3.bar("3×3", val, bottom=bottom, color=col, edgecolor="black",
                linewidth=0.5, hatch=hat, label=lbl, width=0.4)
        ax3.text(0, bottom + val/2, f"{val:.0f}ns",
                 ha="center", va="center", fontsize=8,
                 color="white", fontweight="bold")
        bottom += val
    ax3.set_title("Time Breakdown"); ax3.set_ylabel("ns")
    ax3.set_xticks([]); ax3.legend(fontsize=8)

    # ── 1×1 vs 3×3 per-MAC ───────────────────────────────────────────────────
    ax4 = fig.add_subplot(gs[0, 3])
    categories = ["1×1\n(1 MAC)", "3×3\n(9 MACs)"]
    lat_per_mac = [REF_1x1_LATENCY_NS, lat.mean() / N_PES]
    bars = ax4.bar(categories, lat_per_mac,
                   color=[C_1x1, C_3x3], edgecolor="black", width=0.4)
    for bar, val in zip(bars, lat_per_mac):
        ax4.text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 50, f"{val:.0f}ns",
                 ha="center", va="bottom", fontsize=8, fontweight="bold")
    ax4.set_title("Latency per MAC"); ax4.set_ylabel("ns")
    imp = REF_1x1_LATENCY_NS / (lat.mean() / N_PES)
    ax4.text(0.5, 0.85, f"{imp:.1f}× better/MAC",
             transform=ax4.transAxes, ha="center", fontsize=8,
             color=C_3x3, fontweight="bold")

    # ── Poll histogram ────────────────────────────────────────────────────────
    ax5 = fig.add_subplot(gs[1, 0])
    poll_df = data["poll"]
    polls   = np.repeat(poll_df["total_poll_count"].values,
                        poll_df["frequency"].values)
    bins = np.arange(polls.min() - 0.5, polls.max() + 1.5, 1)
    ax5.hist(polls, bins=bins, color=C_POLL, edgecolor="white", linewidth=0.4)
    ax5.set_title("Poll Distribution"); ax5.set_xlabel("Iterations"); ax5.set_ylabel("Count")

    # ── Throughput comparison ─────────────────────────────────────────────────
    ax6 = fig.add_subplot(gs[1, 1])
    ax6.bar(["1×1", "3×3"], [REF_1x1_THROUGHPUT, 0.2585],
            color=[C_1x1, C_3x3], edgecolor="black", width=0.4)
    ax6.set_title("Throughput (MOPS)"); ax6.set_ylabel("MOPS")
    ax6.text(0.5, 0.85,
             f"{0.2585/REF_1x1_THROUGHPUT:.1f}× improvement",
             transform=ax6.transAxes, ha="center", fontsize=8,
             color=C_3x3, fontweight="bold")

    # ── Scaling projection ────────────────────────────────────────────────────
    ax7 = fig.add_subplot(gs[1, 2:])
    N_values = np.arange(1, 10)
    macs     = N_values ** 2
    thr_proj = macs / (mean_comms + macs * net_per_mac) * 1e6
    thr_ideal = macs / (macs * net_per_mac) * 1e6
    ax7.plot(macs, thr_proj,  "o-", color=C_PROJ,    linewidth=1.8, markersize=5,
             label="Projected")
    ax7.plot(macs, thr_ideal, "s--", color=C_COMPUTE, linewidth=1.5, markersize=4,
             label="Ideal")
    ax7.scatter([1], [REF_1x1_THROUGHPUT], color=C_1x1, s=80, zorder=5,
                label="Measured 1×1")
    ax7.scatter([9], [0.2585], color=C_3x3, s=80, zorder=5,
                label="Measured 3×3")
    ax7.axhline(1.0/(REF_1x1_SW_NS*1e-9)/1e6, color=C_SW, linewidth=1,
                linestyle=":", label="SW baseline")
    ax7.set_title("Throughput Scaling Projection")
    ax7.set_xlabel("MACs (N²)"); ax7.set_ylabel("MOPS")
    ax7.legend(fontsize=8)

    fig.suptitle(
        "IP_SA_3x3 Benchmark Dashboard  –  DE10-Nano  Cyclone V 5CSEBA6U23I7\n"
        "3×3 = 9 PEs  |  50 MHz  |  LW-HPS2FPGA bridge  |  1 000 samples",
        fontsize=11, fontweight="bold"
    )

    save_fig(fig, "fig8_dashboard")
    plt.close(fig)


# =============================================================================
# Entry point
# =============================================================================
def main():
    print("\n" + "=" * 60)
    print("  IP_SA_3x3 Benchmark Plotter  v1.0")
    print("  Output: PDF (vector) + PNG 300 DPI")
    print("=" * 60 + "\n")

    print("Loading data:")
    data = load_data()

    required = ["latency", "comms", "poll"]
    for key in required:
        if key not in data:
            print(f"\n[ERROR] Missing dataset '{key}'. Run sa3x3_benchmark first.\n")
            sys.exit(1)

    print(f"\nGenerating figures → ./{OUTPUT_DIR}/\n")

    plot_latency_histogram    (data)
    plot_latency_cdf          (data)
    plot_boxplot_breakdown    (data)
    plot_stacked_bar          (data)
    plot_poll_histogram       (data)
    plot_comparison_1x1_vs_3x3(data)
    plot_throughput_scaling   (data)
    plot_dashboard            (data)

    print(f"\n{'='*60}")
    print(f"  Done. 8 figures saved to ./{OUTPUT_DIR}/")
    print(f"  PDF (vector, for paper) + PNG (300 DPI, for review)")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
